services:
  - type: web
    name: email-spam-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
    disk:
      - name: data
        sizeGB: 1  # Required for `spam.csv`
    staticPublishPath: templates
